Use which to find fixincl extension.
This is necessary on platforms where it is .exe (OS/2 or Windows).

Note that it didn't affect Windows because fixincl is not run there at all.

diff --git a/fixincludes/fixinc.in b/fixincludes/fixinc.in
--- a/fixincludes/fixinc.in
+++ b/fixincludes/fixinc.in
@@ -94,9 +94,9 @@ esac
 # Original directory.
 ORIGDIR=`${PWDCMD}`
 export ORIGDIR
-FIXINCL=`${PWDCMD}`/fixincl
-if [ ! -x $FIXINCL ] ; then
-  echo "Cannot find fixincl" >&2
+FIXINCL=`which ${ORIGDIR}/fixincl`
+if [ -z "$FIXINCL" ] || [ ! -x $FIXINCL ] ; then
+  echo "Cannot find fixincl in $ORIGDIR" >&2
   exit 1
 fi
 export FIXINCL
